default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: local
    hooks:
      - id: nbqa-black
        name: nbqa-black
        alias: nbqa-black
        entry: nbqa
        args:
          - black
          - "--nbqa-mutate"
          - "--nbqa-config=pyproject.toml"
        language: system
        types: [jupyter]
      - id: nbqa-flake8
        name: nbqa-flake8
        alias: nbqa-flake8
        entry: nbqa
        args:
          - flake8
          - "--nbqa-config=setup.cfg"
        language: system
        types: [jupyter]
      - id: nbqa-isort
        name: nbqa-isort
        alias: nbqa-isort
        entry: nbqa
        args:
          - isort
          - "--nbqa-mutate"
          - "--nbqa-config=.isort.cfg"
        language: system
        types: [jupyter]
